### ISSUE TITLE
Publication on External storage

### ISSUE THREAD

**Issue by cNille** [readium/r2-lcp-kotlin#46]
Hi!

I noticed that the a publication is saved in the external storage in `fetchPublication` ( `r2-lcp/src/main/java/org/readium/r2/lcp/license/License.kt`).  My thought is that internal storage is better because then the files are removed when the app is uninstalled. What are the benefits of storing publications on external storage? 

Would it be possible to set the rootDir in the constructor, or should i just move the publication from external to internal after it is fetched?

**Comment by aferditamuriqi** [comment]
@cNille we'll change this into internal storage in the next tag. and might set an optional rootDir.

**Comment by aferditamuriqi** [comment]
The latest changes in develop now use the internal filesDir for storing publications, to use external filesDir a configuration has been added (see in testapp)
