### ISSUE TITLE
Build on jitpack not available.

### ISSUE THREAD

**Issue by washeeeq** [readium/r2-lcp-kotlin#49]
Hi there,

can you please check, all built versions are built with errors and gradle cannot download from jitpack: https://jitpack.io/#readium/r2-lcp-kotlin

**Comment by aferditamuriqi** [comment]
The r2-lcp-kotlin project doesn't download or compile via jitpack as you need the additional lilcp library to compile it, please see the readme in the testapp or workspace fro more information
