### ISSUE TITLE
SSL in CRLService

### ISSUE THREAD

**Issue by cNille** [readium/r2-lcp-kotlin#59]
Hi!

The newer android versions don't allow HTTP requests by default. So I had to configure in my AndroidManifest to allow HTTP for the CRL to work. Is there a reason for not using HTTPS in this case? :) 

https://github.com/readium/r2-lcp-kotlin/blob/a7960d11f4540ab46fa26afaf6746b0aeae8871c/r2-lcp/src/main/java/org/readium/r2/lcp/service/CRLService.kt#L58

**Comment by HadrienGardeur** [comment]
@llemeurfr this seems to be a legitimate concern, could you confirm that HTTPS is forbidden for the CRL service?

**Comment by llemeurfr** [comment]
The CRL service offered by the provider is indeed a basic http service, with no SSL involved (to be clear https is forbidden).  We have no control on this service.

**Comment by mickael-menu** [comment]
Indeed, the testapp is also setting `android:usesCleartextTraffic` to true, which is not great for confidentiality.

If we could find a way to expose the CRL securely, maybe through an HTTPS proxy, that would be best.

Otherwise, we could improve things by authorizing the HTTP requests only for this domain.

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest>
    <application android:networkSecurityConfig="@xml/network_security_config">
    </application>
</manifest>
```

`network_security_config.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">crl.edrlab.telesec.de</domain>
    </domain-config>
</network-security-config>
```

(I didn't test this solution)

**Comment by llemeurfr** [comment]
I'll come back to the CRL provider (T-systems) and request an https access. Not sure I can obtain it but let's try.

**Comment by llemeurfr** [comment]
Checked with T-Systems. They didn't see CRL distributed via https so far. You may have seen that the CRL is cached via Akamai. The cost of contracting Akamai for an https + caching delivery would be high (certainly too high for us), therefore I fear we'll have to live with an http delivery and corresponding configuration of the client side.

**Comment by mickael-menu** [comment]
I'd like to keep this opened to add the `android:networkSecurityConfig` to authorize HTTP only for the CRL in the testapp.
It might be worth adding it in `r2-lcp-kotlin`'s README as well.

**Comment by mickael-menu** [comment]
`android:networkSecurityConfig` works well and is an acceptable solution IMHO.

See https://github.com/readium/r2-testapp-kotlin/pull/380
