### ISSUE TITLE
Build error caused by the package named `public`

### ISSUE THREAD

**Issue by mickael-menu** [readium/r2-lcp-kotlin#61]
We're facing an issue while trying to use the classes from `org.readium.r2.lcp.public` (imported as a submodule). The build is failing with this error:

`e: java.lang.IllegalStateException: failed to analyze: java.lang.IllegalStateException: processingEnv must not be null`

https://stackoverflow.com/a/59530688

If we rename the `public` package in `r2-lcp-kotlin`, the error disappears.
The weird thing is that this problem doesn't occur in `r2-testapp-kotlin`. Do you have any insights into why @aferditamuriqi?

Regardless of this build error, I think the classes in `public` should be moved to the top-level package anyway.

**Comment by aferditamuriqi** [comment]
these classes were matched to the structure in swift.  and the r2-lcp-kotlin is always used as a submodule since it can't use differently anyway.  But before just moving the package and solving it for one app, it would rather be useful to understand what the differences are in your app vs the testapp. 

I don't have this issue in several apps that I have so far integrated LCP into. So, even more, it would be useful to understand the differences.

**Comment by mickael-menu** [comment]
> I don't have this issue in several apps that I have so far integrated LCP into. So, even more, it would be useful to understand the differences.

Definitely, unfortunately I couldn't find the difference with the testapp after a significant time spent on this...  😕The error happens in a Java file automatically generated by Android Studio from our Kotlin Activity.

Regardless of this build issue, I think it's worth removing `public` because:

- It's not a valid package name
  - https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html
  - https://stackoverflow.com/questions/59105586/cant-compile-the-app-java-lang-illegalstateexception-processingenv-must-not-be/59530688#59530688
- It's not idiomatic to use a package to group public types, and we don't do it anywhere else in our other projects.

To be fair, I think the `Public` folder should be removed from the Swift project as well. It was a mistake from me to add it (bad habit from my C days!). Of course, it's less impacting since there are no packages and folders are a private detail in swift.

**Comment by aferditamuriqi** [comment]
ok, I am fine with removing the public package if we also remove it in swift, to keep things structured the same. still would be worth it to see if any of the settings of the build system are different or outdated.

**Comment by mickael-menu** [comment]
Sure, I have an opened PR on `r2-lcp-swift`, I'll do it there.

I'll check out if the build settings are outdated.
