### ISSUE TITLE
Byte range requests are decrypting the whole resource

### ISSUE THREAD

**Issue by mickael-menu** [readium/r2-lcp-kotlin#69]
I'm opening this issue here but the code is actually in the streamer.

When transforming an input stream through the `DRMDecoder`, the whole resource is read and decrypted in memory, no matter the size of the requested range. This will be a problem for large media files.

https://github.com/readium/r2-streamer-kotlin/blob/develop/r2-streamer/src/main/java/org/readium/r2/streamer/fetcher/DrmDecoder.kt

**Comment by llemeurfr** [comment]
aïe, this kills the performance for EPUB containing audio or video, and audiobooks also.

**Comment by llemeurfr** [comment]
Maybe @aferditamuriqi can give some advice on how to make it work more efficiently.

**Comment by mickael-menu** [comment]
We should be able to adapt the code from Swift:

https://github.com/readium/r2-streamer-swift/tree/develop/r2-streamer-swift/Fetcher/DRM

**Comment by mickael-menu** [comment]
We have crashes in production which I believe are related to this issue. It's probably happening on LCP protected publication with media files too big to be loaded into memory.

```
java.lang.OutOfMemoryError: Failed to allocate a 89037568 byte allocation with 25149440 free bytes and 77MB until OOM, max allowed footprint 212334560, growth limit 268435456
    at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:77)
    at kotlin.io.ByteStreamsKt.readBytes(IOStreams.kt:135)
    at org.readium.r2.streamer.fetcher.DrmDecoder.decipher(DrmDecoder.kt:77)
    at org.readium.r2.streamer.fetcher.DrmDecoder.decoding(DrmDecoder.kt:38)
    at org.readium.r2.streamer.fetcher.ContentFiltersLcp.apply(ContentFilter.kt:335)
    at org.readium.r2.streamer.fetcher.Fetcher.dataStream(Fetcher.kt:43)
    at org.readium.r2.streamer.server.handler.ResourceHandler.get(ResourceHandler.kt:62)
    at org.nanohttpd.router.RouterNanoHTTPD$UriResource.process(RouterNanoHTTPD.java:385)
    at org.nanohttpd.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:597)
    at org.nanohttpd.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:672)
    at org.nanohttpd.protocols.http.NanoHTTPD$1.handle(NanoHTTPD.java:376)
    at org.nanohttpd.protocols.http.NanoHTTPD$1.handle(NanoHTTPD.java:372)
    at org.nanohttpd.protocols.http.NanoHTTPD.handle(NanoHTTPD.java:535)
    at org.nanohttpd.protocols.http.HTTPSession.execute(HTTPSession.java:418)
    at org.nanohttpd.protocols.http.ClientHandler.run(ClientHandler.java:75)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by mickael-menu** [comment]
I started porting the Swift code to Kotlin, but I hit a roadblock. The current implementation of the Fetcher in Kotlin is based on `InputStream`, which only allows to go forward (`mark()` is not supported with `ZipFileInputStream`). But when decrypting, sometimes we have to go backward to align the position with the AES block.

With the [new Fetcher API](https://github.com/readium/architecture/blob/master/proposals/002-composite-fetcher-api.md#methods-1) we moved away from `InputStream` to have a truly random access API. @qnga already implemented it but it's not yet used in the app, so I'm going to replace the existing Fetcher with the new implementation to be able to fix this LCP issue.

**Comment by mickael-menu** [comment]
The fix is implemented in this PR: https://github.com/readium/r2-streamer-kotlin/pull/108/files#diff-d6dcee0574a06761bb6795ee50ddfc41

**Comment by qnga** [comment]
Note that there's still an issue that may lead, as I understand it, the resource to be loaded until its end in case of range request. 

https://github.com/qnga/r2-streamer-kotlin/blob/77fed7eb01f8f97eeb6c67ae2f36928adbcb2bc5/r2-streamer/src/main/java/org/readium/r2/streamer/fetcher/LcpDecryptor.kt#L94

In the `read` function, `range.end` seems to be never used.

**Comment by mickael-menu** [comment]
> Note that there's still an issue that may lead, as I understand it, the resource to be loaded until its end in case of range request.

I think you're right, it looks like I mixed up the `length` variable when [translating from Swift](https://github.com/readium/r2-streamer-swift/blob/7753a9c82e9c44f6211810a313a2f08b5564b235/r2-streamer-swift/Fetcher/DRM/CBCDRMInputStream.swift#L65). Thanks for spotting that!

**Comment by mickael-menu** [comment]
We might have a conceptual issue with `FullLcpResource` as well. Right now, it's intended for compressed entries and reads, decrypts + caches the whole resource, even if we only read a range. This works well for entries which should be compressed, such as HTML files. But if an LCP package is not properly archived and contains large media files with the `deflate` mode, then we might be reading large buffers into memory. This might even trigger an `OutOfMemoryError`.

Maybe a better implementation would be to do no caching, and only read the requested range, but from the start of the stream (because it's deflated). It would be read progressively, discarding buffers that are out of the requested range.

**Comment by mickael-menu** [comment]
> We might have a conceptual issue with `FullLcpResource` as well. Right now, it's intended for compressed entries and reads, decrypts + caches the whole resource, even if we only read a range. This works well for entries which should be compressed, such as HTML files. But if an LCP package is not properly archived and contains large media files with the `deflate` mode, then we might be reading large buffers into memory. This might even trigger an `OutOfMemoryError`.

So far in practice it doesn't seem to be a problem. It could occur with a faulty LCP server implementation which would deflate media files, but this is not the only issue that would happen. In particular, byte range requests would be really slow because reading from the start of the entry for each chunk. In my opinion the server needs to be fixed in this case, and should be considered buggy. So I think we can close this issue for now.
