### ISSUE TITLE
Failed to resolve: readium:liblcp:1.0.0

### ISSUE THREAD

**Issue by Manoj9q** [readium/r2-lcp-kotlin#73]
I am using readium in Android but getting same below errorL

Failed to resolve: readium:liblcp:1.0.0
Show in Project Structure dialog
Affected Modules: r2-lcp
even i have added
        maven { url 'https://jitpack.io' }

**Comment by mickael-menu** [comment]
If you want to use LCP in your app, you need to add this to your `build.gradle`:

```
allprojects {
    repositories {
        ivy {
            url 'https://liblcp.dita.digital'
            patternLayout {
                artifact '/[organisation]/[module]/android/aar/test/[revision].[ext]'
            }
        }
    }
}
```

But if you don't need LCP, don't integrate `r2-lcp-kotlin` in your project. See the instructions here: https://github.com/readium/r2-workspace-kotlin#inttestapp

**Comment by josmilan** [comment]
Is this issue resolved ?

**Comment by mickael-menu** [comment]
@josmilan You need to add another dependency which is private. Please [contact EDRLab](contact@edrlab.org) to get access to the LCP library. If you don't need LCP in your app, don't integrate `r2-lcp-kotlin`. For the test app, don't use the `*-with-lcp` branches in [r2-workspace-kotlin](https://github.com/readium/r2-workspace-kotlin).
