### ISSUE TITLE
In "alpha" branch, "CbcLcpResource" class, incorrect code inside "length()" function

### ISSUE THREAD

**Issue by danielweck** [readium/r2-lcp-kotlin#81]
https://github.com/readium/r2-lcp-kotlin/blob/7448c55fa540fbe108d8ddb28c2b052466895b69/r2-lcp/src/main/java/org/readium/r2/lcp/LCPDecryptor.kt#L88-L90

See the C++ codefix:
https://github.com/readium/readium-lcp-client/commit/25d2e375bc86e662e5611714d18a3c992145641a

https://github.com/readium/readium-lcp-client/blob/21c1ecf43573728279f7e127193f791a17e5a299/src/lcp-client-lib/AesCbcSymmetricAlgorithm.cpp#L126-L134

I'm not sure whether there is equivalent Swift code, please check :)
https://github.com/readium/r2-lcp-swift/tree/alpha/readium-lcp-swift

**Comment by mickael-menu** [comment]
@danielweck Thanks for spotting this! Most likely the Swift version has the same issue because I translated the Kotlin code from Swift (which was translated from C++ 😀)
